### ISSUE TITLE
Weather Issue

### ISSUE THREAD

**Issue by CruzedV** [MikulGamour/Cold-Sweat-Rework-Forge#2]
Hi~! You've made a cool mod, i've enjoyed playing it! But, closer to deal, it's ruining the weather effects in minecraft. 
Here is a list of the mods, plus i installed OptiFine and used the "Sildurs Vibrant Shaders v1.29 Lite" shaders . The Bug appeared and with no shaders. Good Luck!
![image](https://user-images.githubusercontent.com/48482781/133664320-ee0247a4-978c-485a-8632-48d6c1654441.png)

**Comment by MikulGamour** [comment]
How is it ruining the weather effects? We've had some people talk about weather events like rain never occurring in the world, even with commands. Is this your case?
