### ISSUE TITLE
Consider seasons from Serene Seasons

### ISSUE THREAD

**Issue by mfriedrich74** [MikulGamour/Cold-Sweat-Rework-Forge#3]
Can this mod be made to optionally use the seasonal biome temperature from the Serene Seasons mod (e.g. cooler in winter)?

**Comment by MikulGamour** [comment]
This is absolutely planned, yes. The only issue is that Serene Seasons has unfortunately closed its source code in versions past 1.16.5, so if Cold Sweat were yo update to 1.18, for example, Serene Seasons support might have to be dropped.
