### ISSUE TITLE
[Crash] startup crash for unknown reason

### ISSUE THREAD

**Issue by AlienXtream** [MikulGamour/Cold-Sweat-Rework-Forge#4]
unknown mod startup crash.

[crash-2021-10-17_11.39.23-fml.txt](https://github.com/MikulGamour/Cold-Sweat-Rework-Forge/files/7358458/crash-2021-10-17_11.39.23-fml.txt)

**Comment by chubbymomo** [comment]
Hello, Unfortunately we do not have any control over this. The mod Randompatches is causing a mixin error with our mod. We suppose that it is altering the config menu (Escape menu), which, Cold Sweat adds to.

**Comment by AlienXtream** [comment]
ah. fair enough. i could not see that in the report (though knowing what methods are added by what mods and such probably helps). so is there any level of compatibility that can be arranged between the 2 mods? something i can disable on my end without removing it perhaps? what about a compatibility mode that disables the conflicting module if loaded together? (idk a lot about modding from the development side so i dont know whats possible and whats not). its a shame since i would love to check out this mod as it looks exactly like the thing ive been wanting (have been using survive but i like the look of this one more for the temp system)

**Comment by chubbymomo** [comment]
After diagnosing the issue, I can confirm that it is actually a Cold Sweat issue. The way to get around this for now is to only access the Cold Sweat config menu from in-game instead of on the title screen. There will be an update to fix this issue soon.

**Comment by AlienXtream** [comment]
> After diagnosing the issue, I can confirm that it is actually a Cold Sweat issue. The way to get around this for now is to only access the Cold Sweat config menu from in-game instead of on the title screen. There will be an update to fix this issue soon.

appreciate the followup. yeh, day one bugs are a pain XD take your time. i know these are voluntary projects and that other tings like life take precedence. unfortunately as the crash occurs on preloading/startup i never even get to the main menu so the workaround is not relevant in this case but i will be sure to update the mod as soon as a full fix is implemented, whenever that ends up being :)
